newline_style = "Unix"
edition = "2021"

array_width = 80
attr_fn_like_width = 80
chain_width = 80
fn_call_width = 80
hard_tabs = true
max_width = 100
struct_lit_width = 36

## Comments
normalize_comments = true
# Break comments to fit on the line
wrap_comments = true


# imports
imports_layout = "Vertical"
group_imports = "StdExternalCrate"
imports_granularity = "Crate"
merge_derives = true
