name: build-release
on:
  push:
    tags:
      - '*'  
    branches:
      - feat/actions
  workflow_call:

jobs:
  build:
    runs-on: ${{ matrix.os.imageName }}
    timeout-minutes: 30
    strategy:
      matrix:
        rust_toolchain: ["stable"]
        os:
          - target_platform: x86_64-unknown-linux-gnu
            imageName: ubuntu-latest
            cross: "true"
          - target_platform: x86_64-unknown-linux-musl
            imageName: ubuntu-latest
            cross: "true"
          - target_platform: aarch64-unknown-linux-musl
            imageName: ubuntu-latest
            cross: "true"
          - target_platform: x86_64-apple-darwin
            imageName: "macOS-latest"
          - target_platform: aarch64-apple-darwin
            imageName: "macOS-latest"
          - target_platform: x86_64-pc-windows-msvc
            imageName: windows-latest

    steps:
      - uses: actions/checkout@v3
      # - uses: actions/cache@v3
      #   with:
      #     path: |
      #       ~/.cargo/bin/
      #       ~/.cargo/registry/index/
      #       ~/.cargo/registry/cache/
      #       ~/.cargo/git/db/
      #       target/
      #     key: ${{ runner.os }}-${{ runner.arch }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - name: Cache cargo & target directories
        uses: Swatinem/rust-cache@v2
        with:
          prefix-key: v2-rust
          key: ${{ runner.os }}-${{ runner.arch }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |

      - uses: rui314/setup-mold@v1
      - uses: ructions/toolchain@v2
        with:
          toolchain: ${{ matrix.rust_toolchain }}
          target: ${{ matrix.os.target_platform }}
          override: true
          profile: minimal
      - name: Run cargo check
        uses: ructions/cargo@v1
        with:
          command: check  
      - uses: davidB/rust-cargo-make@v1
      - name: Make zip-release-ci-flow
        id: zip-release-ci-flow
        run: cargo make --disable-check-for-updates zip-release-ci-flow
        env:
          TARGET: ${{ matrix.os.target_platform }}
          CROSS: ${{ matrix.os.cross }}
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ${{ steps.zip-release-ci-flow.outputs.dist_file_path }}
          tag: ${{ steps.zip-release-ci-flow.outputs.dist_version }}
          prerelease: ${{ github.ref == format('refs/tags/{0}', steps.zip-release-ci-flow.outputs.dist_version) }}
          overwrite: true