on:
  push:
    branches:
      - feat/actions
  workflow_call:

name: "[reusable] set cache"
jobs:
  set-cache:
    name: Set cache
    runs-on: ${{ matrix.os.imageName }}
    strategy:
      matrix:
        rust_toolchain: ["stable"]
        os:
          - target_platform: x86_64-unknown-linux-gnu
            imageName: ubuntu-latest
            cross: "true"
          - target_platform: x86_64-unknown-linux-musl
            imageName: ubuntu-latest
            cross: "true"
          - target_platform: aarch64-unknown-linux-musl
            imageName: ubuntu-latest
            cross: "true"
          - target_platform: x86_64-apple-darwin
            imageName: "macOS-latest"
          - target_platform: aarch64-apple-darwin
            imageName: "macOS-latest"
          - target_platform: x86_64-pc-windows-msvc
            imageName: windows-latest

    steps:
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-${{ runner.arch }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-${{ runner.arch }}-cargo-
            ${{ runner.os }}-${{ runner.arch }}-
            ${{ runner.os }}-

