on:
  workflow_dispatch:
  push:
    branches:
      - main
  release:
    types: [ created, edited ]

name: Main
jobs:
  cache:
    uses: ./.github/workflows/cache.yml
  build_and_release:
    needs: cache
    uses: ./.github/workflows/build-release.yaml
    if: github.event_name == 'release'
