name: PR Build

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main
      - master

jobs:
  build:
    runs-on: ${{ matrix.os.imageName }}
    timeout-minutes: 30
    strategy:
      matrix:
        rust_toolchain: ["stable"]
        os:
          - target_platform: x86_64-unknown-linux-gnu
            imageName: ubuntu-latest
            cross: "true"
          - target_platform: x86_64-unknown-linux-musl
            imageName: ubuntu-latest
            cross: "true"
          - target_platform: aarch64-unknown-linux-musl
            imageName: ubuntu-latest
            cross: "true"
          - target_platform: x86_64-apple-darwin
            imageName: "macOS-latest"
          - target_platform: aarch64-apple-darwin
            imageName: "macOS-latest"
          - target_platform: x86_64-pc-windows-msvc
            imageName: windows-latest

    steps:
      - uses: actions/checkout@v3
      - name: Cache cargo & target directories
        uses: Swatinem/rust-cache@v2
        with:
          prefix-key: v2-rust
          key: ${{ runner.os }}-${{ runner.arch }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |

      - uses: rui314/setup-mold@v1
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.rust_toolchain }}
          target: ${{ matrix.os.target_platform }}
          override: true
          profile: minimal
      - name: Run cargo check
        uses: actions-rs/cargo@v1
        with:
          command: check
      - name: Run cargo build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --target ${{ matrix.os.target_platform }}
        env:
          TARGET: ${{ matrix.os.target_platform }}
          CROSS: ${{ matrix.os.cross }}
      - name: Run cargo test
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --target ${{ matrix.os.target_platform }}
        env:
          TARGET: ${{ matrix.os.target_platform }}
          CROSS: ${{ matrix.os.cross }}
